Alt/urls.py
from django.urls import path
from .views import home, ShirtList, view_shirt, NonProfitList, view_nonProfit, add_to_cart, remove_from_cart, OrderSummaryView, reduce_quantity_from_cart,CheckoutView, UserDetailView, dontation_page

app_name= 'Alt'

urlpatterns = [
    path('', home, name='landing'),
    path('allshirts', ShirtList.as_view(), name = 'allshirts_list'),
    
    path('true/<slug>',  dontation_page, name= 'user'),
    path('shirt/<slug>/', view_shirt, name = 'shirts' ),
    path('all_nonprofits', NonProfitList.as_view(), name='nonprofit_list'),
    path('nonprofit/<slug>', view_nonProfit, name='nonprofit' ),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/',remove_from_cart, name='remove-from-cart' ),
    path('order-summary', OrderSummaryView.as_view(), name ='order_summary'),
    path('reduce-quantity-from-cart/<slug>/', reduce_quantity_from_cart, name='reduce-quantity-from-cart'),
    path('chekout', CheckoutView.as_view(), name='checkout'),
    

    
    
   
]

config/urls.py
from django.conf.urls import include, url
from django.conf import settings

from django.urls import path
import Alt, StripeAPI
from rest_framework.authtoken.views import obtain_auth_token
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('api.urls')),
    url(r'^auth/', include('rest_auth.urls')),
    path('secure/', obtain_auth_token),
    url(r'^auth/registration/', include('rest_auth.registration.urls')),
    path('', include('Alt.urls')),
    url(r'^payments/', include('StripeAPI.urls', namespace='StripeAPI')),
    path('accounts/', include('allauth.urls')),
    path('verification/', include('verify_email.urls')),
 

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Alt/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.template.defaultfilters import slugify
from django.db.models.signals import pre_save
from api.models import UserProfile, User
from django.core.validators import MinValueValidator, MaxValueValidator


class Country(models.Model):
    name= models.CharField( max_length=50, blank=False, null=False)
    flag =models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return self.name


class Atrocity(models.Model):
    title = models.CharField(max_length=30, blank=False, null=False)
    region = models.CharField(max_length=30, blank=False, null=False)
    info= models.TextField()
    image_url = models.TextField()
    category = models.ManyToManyField('Category', related_name='Atrocity')
    country = models.ForeignKey(Country, on_delete=models.CASCADE,blank=True, null=True )
    slug = models.SlugField(unique = True) 
    featured= models.BooleanField(blank=True, null=True)
    date_added= models.DateTimeField( auto_now_add=True)
    videoURL= models.URLField( max_length=200)

    

    def __str__(self):
        return self.title
    def slug(self):
        return slugify(self.title)        

    def get_absolute_url(self):
        return reverse ('Alt:Atrocity', kwargs={'slug':self.slug})




class Shirt(models.Model):
    name = models.CharField(max_length=30, blank=False, null=False)
    price = models.FloatField()
    discount_price = models.FloatField()
    shirt_type = models.CharField(max_length=30, blank=False, null=False) 
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    shirt_image = models.CharField( max_length=100)
    original_image = models.CharField(max_length =100)
    Atrocity = models.ManyToManyField(Atrocity, related_name='Shirt', blank=True)
    slug = models.SlugField(unique = True, null=True, blank=True)
    featured = models.BooleanField(blank=True, null=True)
    date_added= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

    def addToCart(self):
        return reverse('core: add-to-cart', kwargs={
            'slug':self.slug
        })

    
    def removeFromCart(self):
        return reverse( 'core: remove-from-cart', kwargs={
            'slug':self.slug
        })


    def get_absolute_url(self):
        return reverse("Alt:shirts", kwargs={"slug": self.slug})

    def no_of_ratings(self):
        ratings = Rating.objects.filter(shirt =self)
        return len(ratings)

    def average_rating(self):
        sum = 0
        ratings = Rating.objects.filter(shirt =self)
        for rating in ratings:
            sum += rating.stars
        if len(ratings) > 0:
            return sum /len(ratings)
        else:
            return 0


def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug='SLUG'

pre_save.connect(slug_generator, sender=Shirt)    
    
class Rating(models.Model):
    shirt = models.ForeignKey("Alt.Shirt", on_delete=models.CASCADE)
    user = models.ForeignKey("api.User", on_delete=models.CASCADE)
    stars = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])

    class Meta:
        unique_together = (('user', 'shirt'),)
        index_together = (('user', 'shirt'),)


    def __str__(self):
        return self.shirt.name

    def get_absolute_url(self):
        return reverse("Rating_detail", kwargs={"pk": self.pk})


class Category(models.Model):
    name = models.CharField(max_length = 50, blank=False, )
    image = models.CharField(max_length=50)
    information =models.TextField()
    shirtList = models.ManyToManyField("Shirt", related_name='Category', blank=True, )
    nonProfitList = models.ManyToManyField("NonProfit", related_name='Category', blank=True, )

    def __str__(self):
        return self.name
    
 


class NonProfit(models.Model):
    name= models.CharField(max_length=50, blank=False, null=False)
    logo =  models.TextField()
    description =models.TextField()
    year_started = models.IntegerField()
    mission_statement=models.TextField()
    vision_statement=models.TextField()
    website_url= models.URLField()
    category = models.ManyToManyField(Category, related_name='NonProfit')
    slug = models.SlugField(unique = True)
    featured = models.BooleanField(blank=True, null=True)
    date_added= models.DateTimeField(auto_now_add=True)
    atrocity = models.ManyToManyField(Atrocity, blank=True, null=True, related_name='NonProfit')
    shirtList=models.ManyToManyField("Shirt",related_name='NonProfit' )
    main_image= models.CharField(max_length=200)
    

    def get_absolute_url(self):
        return reverse("Alt:NonProfit", kwargs={"slug": self.slug})
    



    def __str__(self):
        return self.name

    
class OrderItem(models.Model):
    user = models.ForeignKey("api.UserProfile", on_delete=models.CASCADE)
    ordered_shirt = models.ForeignKey("Alt.Shirt", on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    
    def __str__(self):
        return f'{self.quantity} of {self.ordered_shirt.name}'


    def get_total_shirt_price(self):
        return self.quantity * self.ordered_shirt.price

    def get_discount_shirt_price(self):
        return self.quantity * self.ordered_shirt.discount_price

    def get_amount_donated(self):
        return self.get_total_shirt_price() * .35

    def get_final_price(self):
        if self.ordered_shirt.discount_price:
            return self.get_discount_shirt_price()
        return self.get_total_shirt_price()


class Order(models.Model):
    user = models.ForeignKey("api.UserProfile", on_delete=models.CASCADE)
    shirts = models.ManyToManyField("Alt.OrderItem")
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    completed = models.BooleanField(default = False)

    def __str__(self):
        return self.user.email

    def get_total_price(self):
        total = 0
        for order_item in self.shirts.all():
            total += OrderItem.get_final_price()
        return total



class CheckoutAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100, blank=True, null=True)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return self.user.email

Alt/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


PAYMENT = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)

class CheckoutForm(forms.Form):
    street_address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': '1234 Main St'
    }))
    apartment_address = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Apartment or suite'
    }))
    country = CountryField(blank_label='(select country)').formfield(widget=CountrySelectWidget(attrs={
        'class': 'custom-select d-block w-100'
    }))
    zip = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    same_billing_address = forms.BooleanField(required=False)
    save_info = forms.BooleanField(required=False)
    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT)

Alt/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View
from .models import Shirt, Atrocity, NonProfit, Order, OrderItem, CheckoutAddress
from django.contrib import messages
from api.models import User, UserProfile
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from .forms import CheckoutForm



def home(request):
  return render (request, 'landing.html')






class UserDetailView(DetailView):
  model = UserProfile
  
   

  def get_object(self, queryset=None):
    
    return self.model.objects.filter(slug='slug')
    
  def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context['shirt_list'] = Shirt.objects.all()
        context['atrocity_list']= Atrocity.objects.all()
        context['nonProfit_list'] = NonProfit.objects.all()
        context['slug'] = 'slug'

        return context



def dontation_page(request, slug):
  user = get_object_or_404(UserProfile, slug =slug)
  return render (request, 'user.html', {'user':user})


class ShirtList(ListView):
  model = Shirt
  template_name = 'allshirts_list.html'


def view_shirt(request, slug):
  shirt = get_object_or_404(Shirt, slug=slug)

  return render(request, 'shirt.html',{'shirt':shirt} )



class NonProfitList(ListView):
  model = NonProfit
  template_name = 'nonprofit_list.html'


def view_nonProfit(request, slug):
  nonprofit = get_object_or_404(NonProfit, slug=slug)

  return render(request,'nonprofit.html', {'nonprofit':nonprofit} )


@login_required
def add_to_cart(request, slug) :
    shirt = get_object_or_404(Shirt, slug = slug )
    order_item, created = OrderItem.objects.get_or_create(
        shirt=shirt,
        user = request.User,
        ordered = False
    )
    order_qs = Order.objects.filter(user=request.User, ordered= False)

    if order_qs.exists() :
        order = order_qs[0]
        
        if order.items.filter(item__pk = shirt.pk).exists() :
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "Added quantity Item")
            return redirect("Alt:shirts", slug = slug)
        else:
            order.items.add(order_item)
            messages.info(request, "Item added to your cart")
            return redirect("Alt:shirts", slug = slug)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.User, ordered_date = ordered_date)
        order.items.add(order_item)
        messages.info(request, "Item added to your cart")
        return redirect("Alt:shirts", slug = slug)

@login_required
def remove_from_cart(request, slug):
    shirt = get_object_or_404(Shirt, slug=slug )
    order_qs = Order.objects.filter(
        user=request.User, 
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(shirt__slug=shirt.slug).exists():
            order_item = OrderItem.objects.filter(
                shirt=shirt,
                user=request.User,
                ordered=False
            )[0]
            order_item.delete()
            messages.info(request, "Item \""+order_item.ordered_shirt.name+"\" remove from your cart")
            return redirect("Alt:shirts", slug = slug)
        else:
            messages.info(request, "This Item not in your cart")
            return redirect("Alt:shirts", slug=slug)
    else:
        #add message doesnt have order
        messages.info(request, "You do not have an Order")
        return redirect("Alt:shirts", slug = slug)



class OrderSummaryView(LoginRequiredMixin, View):
  def get(self, *args, **kwargs):

    try:
      order = Order.objects.get(user=self.request.User, ordered =False)
      context={
        'object':order
      }
      return render(self.request, 'order_summary.html', context)
    except ObjectDoesNotExist:
      messages.error(self.request, 'You do not have an order')
      return redirect ('/')


@login_required
def reduce_quantity_from_cart(request, slug):
  shirt = get_object_or_404(Shirt, slug=slug)
  order_qs = Order.objects.filter(
    user = request.User, 
    ordered = False
  )
  if order_qs.exists():
    order = order_qs[0]
    if order.shirts.filter(shirt__slug=shirt.slug).exists():
      ordered_shirt = OrderItem.objects.filter(
        ordered_shirt = shirt,
        user = request.User,
        ordered = False
      )[0]
      if ordered_shirt.qauntity > 1:
        ordered_shirt.quantity -=1
        ordered_shirt.save
      else:
        ordered_shirt.delete()
      messages.info(request, 'Item quantity has been updated')
      return redirect('Alt:order-summary')
    else:
      messages.info(request, 'This item is not in your cart')
      return redirect("Alt:order-summary")
  else:
    messages.info(request, "You have not started an order")
    return redirect("Allt:order-summary")


class CheckoutView(View):
    def get(self, *args, **kwargs):
        form = CheckoutForm()
        context = {
            'form': form
        }
        return render(self.request, 'checkout.html', context)

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        
        try:
            order = Order.objects.get(user=self.request.User, ordered=False)
            if form.is_valid():
                street_address = form.cleaned_data.get('street_address')
                apartment_address = form.cleaned_data.get('apartment_address')
                country = form.cleaned_data.get('country')
                zip = form.cleaned_data.get('zip')
                same_billing_address = form.cleaned_data.get('same_billing_address')
                save_info = form.cleaned_data.get('save_info')
                payment_option = form.cleaned_data.get('payment_option')

                checkout_address = CheckoutAddress(
                    user= self.request.User,
                    street_address=street_address,
                    apartment_address=apartment_address,
                    country=country,
                    zip=zip
                )
                checkout_address.save()
                order.checkout_address = checkout_address
                order.save()
                return redirect('Alt:checkout')
            messages.warning(self.request, "Failed Chekout")
            return redirect('Alt:checkout')

        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have an order")
            return redirect("Alt:order-summary")

  

Alt/templates/allshirts_list.html
hey

Alt/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
      crossorigin="anonymous"
    />

    <title>Altrue Global</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css"
    />

    <!-- new -->

    <script
      defer
      src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"
    ></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="#">Something else here</a>
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <a
                class="nav-link disabled"
                href="#"
                tabindex="-1"
                aria-disabled="true"
                >Disabled</a
              >
            </li>
          </ul>
          <form class="d-flex">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>

    {% block content %} {% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
      crossorigin="anonymous"
    ></script>

    {% block scripts %} {% endblock %}

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

Alt/templates/landing.html
{% extends 'base.html' %} {% load static %} {% block content %}

<h1>Welcome To Altrue Global</h1>

{% endblock %}

Alt/templates/nonprofit.html
hey
idit

Alt/templates/nonprofit_list.html
hey

Alt/templates/qrpage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>{{name}}:{{obj.user.name}}</h1>
    <img src="{{obj.qr_code.url}}" alt="" />
  </body>
</html>

Alt/templates/user.html
{% extends 'base.html' %} {% load static %} {% block script %}
<script src="https://js.stripe.com/v3/"></script>
<!-- new -->

<script src="{% static 'main.js' %}"></script>
{% endblock script %} {% block content %}
<div class="TY Message">
  <h1>Thank You</h1>
  <p>
    You are visiting {{ user.slug }}'s Altrue Page. Here you can learn about the
    causes and world issues they care about the most, and possibly make a
    donation to a non profit of {{ user.slug }}'s choice.
  </p>
  <img src="{{ user.qr_code_img }}" alt="{{ user.slug }}'s qr code" />
</div>
<button class="button is-primary" id="submitBtn">Purchase!</button>

{% for shirt in user.shirt_list.all %}
<div class="ShirtList">
  <h1>{{ shirt.name }}</h1>
  {% for atrocity in shirt.Atrocity.all %}
  <p>{{ atrocity.title }}</p>

  {% endfor %}

  <img
    src="{{ shirt.shirt_image }}"
    alt="{{ shirt.name }}"
    width="450"
    height="450"
  />
</div>

<div class="NPlist">
  {% for nonprofit in user.nonProfit_list.all %}

  <h2>
    <a href="{% url 'Alt:nonprofit' nonprofit.slug %}">{{ nonprofit.name }} </a>
  </h2>
  {% endfor %}
</div>
{% endfor %}

<section class="section">
  <div class="container">
    <button class="button is-primary" id="submitBtn">Purchase!</button>
  </div>
</section>

{% endblock content %}

Alt/templates/userprofile.html
{% extends "base.html" %} {% block content %}

<h1>{{ user.slug }}</h1>

{% for shirt in user.shirt_list %}
<h1>{{ shirt.name }}</h1>

{% endfor %} {% endblock %}